# Generated by Django 5.0.6 on 2024-12-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project3.course', verbose_name='Kurs')),
            ],
        ),
    ]
